site_name: "mkdocstrings"
site_description: "Automatic documentation from sources, for MkDocs."
site_url: "https://mkdocstrings.github.io/"
repo_url: "https://github.com/mkdocstrings/mkdocstrings"
edit_uri: "blob/master/docs/"
repo_name: "mkdocstrings/mkdocstrings"

nav:
- Overview: index.md
- Usage:
  - usage.md
  - Theming: theming.md
  - Handlers:
    - handlers/overview.md
    - Python: handlers/python.md
    - Crystal: https://mkdocstrings.github.io/crystal/
  - Troubleshooting: troubleshooting.md
- Code Reference:
  - mkdocstrings:
    - handlers:
      - base.py: reference/handlers/base.md
      - rendering.py: reference/handlers/rendering.md
      - python.py: reference/handlers/python.md
    - extension.py: reference/extension.md
    - inventory.py: reference/inventory.md
    - loggers.py: reference/loggers.md
    - plugin.py: reference/plugin.md
  - mkdocs_autorefs:
    - references.py: reference/autorefs/references.md
    - plugin.py: reference/autorefs/plugin.md
- Contributing:
  - contributing.md
  - Code of Conduct: code_of_conduct.md
  - Coverage report: coverage.md
- Changelog: changelog.md
- Credits: credits.md
- License: license.md

theme:
  name: material
  palette:
    scheme: preference
    primary: teal
    accent: purple

extra_css:
- css/style.css

markdown_extensions:
- admonition
- pymdownx.emoji
- pymdownx.magiclink
- pymdownx.snippets:
    check_paths: true
- pymdownx.superfences
- pymdownx.tabbed
- pymdownx.tasklist
- toc:
    permalink: "¤"

plugins:
- search
- gen-files:
    scripts:
    - docs/gen_credits.py
    - docs/gen_doc_stubs.py
- section-index
- coverage:
    html_report_dir: build/coverage
- mkdocstrings:
    handlers:
      python:
        setup_commands:
        - import sys
        - sys.path.append("docs")
        selection:
          new_path_syntax: yes
    watch:
    - src/mkdocstrings
