site_name: "mkdocstrings"
site_description: "Automatic documentation from sources, for MkDocs."
site_url: "https://pawamoy.github.io/mkdocstrings"
repo_url: "https://github.com/pawamoy/mkdocstrings"
repo_name: "pawamoy/mkdocstrings"

nav:
- Overview: index.md
- Usage: usage.md
- Handlers:
  - Overview: handlers/overview.md
  - Python: handlers/python.md

- Code Reference:
  - mkdocstrings:
    - handlers:
      - base.py: reference/handlers/base.md
      - python.py: reference/handlers/python.md
    - extension.py: reference/extension.md
    - plugin.py: reference/plugin.md
  - mkdocs_autorefs:
    - references.py: reference/autorefs/references.md
    - plugin.py: reference/autorefs/plugin.md

- Troubleshooting: troubleshooting.md
- Contributing: contributing.md
- Code of Conduct: code_of_conduct.md
- Changelog: changelog.md
- Credits: credits.md
- License: license.md

theme:
  name: material
  palette:
    scheme: slate
    primary: teal
    accent: purple

extra_css:
- css/mkdocstrings.css

markdown_extensions:
- admonition
- pymdownx.emoji
- pymdownx.magiclink
- pymdownx.snippets:
    check_paths: true
- pymdownx.superfences
- pymdownx.tabbed
- pymdownx.tasklist
- toc:
    permalink: "¤"

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        setup_commands:
        - import sys
        - sys.path.append("docs")
        selection:
          new_path_syntax: yes
    watch:
    - src/mkdocstrings
